server:
  port: 8083

spring:
  application:
    name: transaction-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:5557/vbank_transactions?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USER:vbank_user}
    password: ${MYSQL_PASSWORD:vbank_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    logging-topic: logging

account-service:
  url: ${ACCOUNT_SERVICE_URL:http://localhost:8082}
